import WebSocket from 'ws';
import { createServer } from './index.js';
const ok = (c, m) => { console.log((c ? 'OK   ' : 'FAIL ') + m); if (!c) process.exitCode = 1; };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const srv = createServer({ port: 0, minPlayers: 0 }); await new Promise((r) => srv.wss.on('listening', r)); const port = srv.wss.address().port;
const room = srv.rooms[0], C = room.T.CAVES;
ok(C.length >= 3, 'el mapa tiene cuevas: ' + C.length);
const ws = new WebSocket('ws://localhost:' + port); const msgs = []; await new Promise((r) => ws.on('open', r)); ws.on('message', (d) => msgs.push(JSON.parse(d)));
ws.send(JSON.stringify({ t: 'join', name: 'Ana', token: 'ana', map: 'isla' })); await sleep(300);
const p = [...room.players.values()][0], c = C[0], send = (m) => ws.send(JSON.stringify(m));
send({ t: 'cave', id: 0, dir: 'in' }); await sleep(100); ok(p.cave == null, 'lejos de la boca no se puede entrar');
p.x = c.ex; p.z = c.ez; p.y = c.y; p.prot = 0;
send({ t: 'cave', id: 0, dir: 'in' }); await sleep(150);
ok(p.cave === 0 && p.x > room.half + 100 && p.y === c.in.y, 'junto a la boca se entra en la cueva');
ok(msgs.some((m) => m.t === 'tp' && m.cave === 0), 'el cliente recibe el teletransporte');
send({ t: 'pos', x: p.x + 3, y: p.y, z: p.z, yaw: 0 }); await sleep(100); ok(Math.abs(p.x - (c.in.x - c.in.R + 2.5 + 3)) < .1, 'dentro de la cueva el movimiento se acepta');
send({ t: 'pos', x: p.x + 40, y: p.y, z: p.z, yaw: 0 }); await sleep(100); ok(p.x < c.in.x + c.in.R, 'no se puede salir de las paredes de la cueva');
send({ t: 'build', piece: { kind: 'foundation', i: 1, j: 1, top: 1, bottom: 0, key: 'x' } }); await sleep(100); ok(room.B.map.size === 0, 'no se puede construir dentro');
send({ t: 'cave', id: 0, dir: 'out' }); await sleep(100); ok(p.cave != null, 'lejos de la salida interior no se puede salir');
p.x = c.in.x - c.in.R + 2.5; p.z = c.in.z; await sleep(1100);
send({ t: 'cave', id: 0, dir: 'out' }); await sleep(150); ok(p.cave == null && Math.hypot(p.x - c.ex, p.z - c.ez) < .1, 'junto a la salida se vuelve a la superficie');
srv.close(); process.exit(process.exitCode || 0);
